version: '3.8'
services:
  mc:
    image: itzg/minecraft-server
    container_name: gs_mc_lobby
    environment:
      EULA: true
      ENABLE_RCON: true
      TYPE: PAPER
      VERSION: 1.19.2
      MOTD: "LOONY-ARCADE Lobby"
      SERVER_NAME: "LOONY-ARCADE Lobby"
      TZ: "Europe/Berlin"
      SERVER_PORT: 25565
      MAX_PLAYERS: 5
      MEMORY: 4G
      CONSOLE: true
      OVERRIDE_ICON: true
      OPS_FILE: ""
      ICON: ""
      ALLOW_NETHER: false
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      ENABLE_COMMAND_BLOCK: false
      FORCE_GAMEMODE: true
      GENERATE_STRUCTURES: true
      HARDCORE: false
      SNOOPER_ENABLED:  false
      MAX_BUILD_HEIGHT: 256
      MAX_TICK_TIME:  60000
      SPAWN_ANIMALS: true
      SPAWN_MONSTERS:  false
      SPAWN_NPCS: true
      SPAWN_PROTECTION: 9999
      VIEW_DISTANCE:  10
      MODE: survival
      PVP:  false
      RESOURCE_PACK: ""
      LEVEL:  "lobby"
      ONLINE_MODE: false
      ALLOW_FLIGHT: false
      PLAYER_IDLE_TIMEOUT: 5
      SYNC_CHUNK_WRITES: true
      NETWORK_COMPRESSION_THRESHOLD: 512
      ENFORCE_WHITELIST: true
      ENABLE_WHITELIST: true
      SIMULATION_DISTANCE:  20
      
    ports:
      - 25575:25565
      - 8123:8123
      - 3306:3306
    volumes:
      - /mnt/user/appdata/gs_mc_homierepublic:/data
    restart: unless-stopped