version: '3.8'
services:
  mc:
    image: itzg/minecraft-server
    container_name: gs_mc_lobby
    environment:
      EULA: true
      ENABLE_RCON: true
      TYPE: PAPER
      VERSION: 1.19.2
      MOTD: "LOONY-ARCADE LOGIN SERVER"
      SERVER_NAME: "LOONY-ARCADE LOGIN SERVER"
      TZ: "Europe/Berlin"
      SERVER_PORT: 25565
      MAX_PLAYERS: 50
      MEMORY: 2G
      CONSOLE: true
      OVERRIDE_ICON: true
      ICON: ""
      ALLOW_NETHER: false
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      ENABLE_COMMAND_BLOCK: false
      FORCE_GAMEMODE: true
      GENERATE_STRUCTURES: true
      HARDCORE: false
      SNOOPER_ENABLED:  false
      MAX_BUILD_HEIGHT: 256
      MAX_TICK_TIME:  60000
      SPAWN_ANIMALS: true
      SPAWN_MONSTERS:  false
      SPAWN_NPCS: true
      SPAWN_PROTECTION: 9999
      VIEW_DISTANCE:  15
      MODE: survival
      PVP:  false
      RESOURCE_PACK: ""
      LEVEL:  "lobby"
      ONLINE_MODE: false
      ALLOW_FLIGHT: false
      PLAYER_IDLE_TIMEOUT: 5
      SYNC_CHUNK_WRITES: true
      NETWORK_COMPRESSION_THRESHOLD: 512
      ENFORCE_WHITELIST: false
      ENABLE_WHITELIST: false
      SIMULATION_DISTANCE:  20
      stdin_open: true
      tty: true
      
    ports:
      - 25575:25565
    volumes:
      - /mnt/user/appdata/gs_mc_lobby:/data
    networks:
      default:
        external:
            name: gameserver

    restart: unless-stopped
